# log dir 
log_dir: ~/logs/clip_moev4_1_4_0_7_k1_n6_g2_s1_888161632_81632486496128_1e-4_3e-5_842

label_config: train_config
clip_pretrained: ./pretrained/ViT-B-16.pt   # path to a pre-trained model, if using one
vit_pretrained: ~/.cache/torch/hub/checkpoints/ViT-B_16.npz
pretrained: ~/05_deepfake/DeepfakeBench/training/logs/clip_lora_r24/test/Celeb-DF-v1/ckpt_best.pth  # path to a pre-trained model, if using one
model_name: ClipMoev4_1_4_0_7
backbone_name: vit
use_distillation_loss: false
prompt_init: this_face_photo_is
prompt_classnames: [
   'fake','face-swapped', 'edited in facial expressions','manipulated in facial attributes'
]
backbone_config:
  mode: original
  num_classes: 512
  embed_dim: 768
  token_dim: 8

  attn_adapter_topk: 1
  attn_adapter_dim: [8, 16, 32, 48, 64, 96, 128]
  attn_adapter_deep2idx: {0:[0, 1, 2, 3, 4, 5, 6]}
  attn_adapter_link_group: 7
  attn_adapter_link_stride: 1
  attn_adapter_name: ['qkv']
  attn_adapter_type: 'reshape'

  mlp_adapter_topk: 1
  mlp_adapter_dim: [8, 8, 8, 16, 16, 32]
  mlp_adapter_deep2idx: {0: [0, 1, 2], 1: [3, 4], 2: [5]}
  mlp_adapter_link_group: 2
  mlp_adapter_link_stride: 1
  mlp_adapter_name : ['mlp']
  mlp_adapter_type: 'mean'
  inc: 3
  dropout: false

# dataset
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [FaceForensics++]
#test_dataset: [Celeb-DF-v1, Celeb-DF-v2, DeepFakeDetection, DFDC, DFDCP]
test_dataset: [Celeb-DF-v2, DeepFakeDetection, DFDC, DFDCP]
# 只要是pair 就是两类label
train_dataset_type: pairDataset
test_dataset_type: DeepfakeAbstractBaseDataset

compression: c23  # compression-level for videos
train_batchSize: 32   # training batch size
test_batchSize: 64   # test batch size
workers: 4   # number of data loading workers
frame_num: {'train': 32, 'test': 32}   # number of frames to use per video in training and testing
resolution: 224   # resolution of output image to network
with_mask: false   # whether to include mask information in the input
with_landmark: false   # whether to include facial landmark information in the input

# data augmentation
use_train_data_augmentation: false  # Add this flag to enable/disable data augmentation
use_test_data_augmentation: false  # Add this flag to enable/disable data augmentation
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100
  noise_limit_lower: 0*255**2
  noise_limit_upper: 0*255**2

test_data_aug: [GNC]
test_level: 3
# mean and std for normalization
mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

# optimizer config
optimizer:
  # choose between 'adam' and 'sgd'
  type: adam
  adam:
    lr: 1e-4  # learning rate
    other_lr: 3e-5
    beta1: 0.9  # beta1 for Adam optimizer
    beta2: 0.999 # beta2 for Adam optimizer
    eps: 0.00000001  # epsilon for Adam optimizer
    weight_decay: 0.0005  # weight decay for regularization
    amsgrad: false

# training config
lr_scheduler:
  type: MultiStepLR
  step_size: 960000 # 32*30000
nEpochs: 15   # number of epochs to train for
start_epoch: 0   # manual epoch number (useful for restarts)
save_epoch: 1   # interval epochs for saving models
rec_iter: 100   # interval iterations for recording
save_ckpt: true   # whether to save checkpoint
save_feat: false   # whether to save features

# loss function
loss_func: cross_entropy   # loss function to use
losstype: null

# metric
metric_scoring: auc   # metric for evaluation (auc, acc, eer, ap)

cuda: true   # whether to use CUDA acceleration
cudnn: true   # whether to use CuDNN for convolution operations

dataset_json_folder: './preprocessing/dataset_json'
label_dict:
  # FF++ + FaceShifter(FF-real+FF-FH)
#  FF-FH: 5
#  FF-SH: 6
  FF-DF: 1
  FF-FS: 1
  FF-NT: 1
  FF-F2F: 1
  FF-real: 0
  # CelebDF
  CelebDFv1_real: 0
  CelebDFv1_fake: 1
  CelebDFv2_real: 0 # 178
  CelebDFv2_fake: 1 # 340
  # DFD
  DFD_fake: 1 # 3066
  DFD_real: 0 # 363
  # DFDCP
  DFDCP_Real: 0 # 230
  DFDCP_FakeA: 1 # 397
  DFDCP_FakeB: 1 # 27
  # DFDC
  DFDC_Fake: 1 # 2389
  DFDC_Real: 0 # 2315
  # DeeperForensics-1.0
  DF_fake: 1
  DF_real: 0
  # UADFV
  UADFV_Fake: 1
  UADFV_Real: 0
  # Roop
  roop_Real: 0
  roop_Fake: 1